[package]
name = "cloudflare-ddns"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Poisson"]

[dependencies]
dotenv = "0.15.0"
log = "0.4.20"
env_logger = "0.10.1"
anyhow = "1.0.77"
cloudflare = { version = "0.11.0" , features = ["rustls-tls", "blocking"], default-features=false }
reqwest = { version = "0.11.23", features = ["rustls-tls", "json", "blocking"], default-features=false }
rustls = "0.22.1"
rustls-pemfile = "2.0.0"
webpki-roots = "0.26.0"

[profile.release]
lto = true
codegen-units = 1