[package]
name = "cloudflare-ddns"
version = "0.1.0"
edition = "2021"
authors = ["Jonathan Poisson"]

[dependencies]
dotenv = "0.15.0"
log = "0.4.20"
env_logger = "0.10.0"
anyhow = "1.0.75"
cloudflare = { version = "0.10.1" , features = ["rustls-tls"], default-features=false }
reqwest = { version = "0.11.20", features = ["rustls-tls", "json", "blocking"], default-features=false }
rustls = "0.21.7"
rustls-pemfile = "1.0.0"
webpki-roots = "0.25.0"

[profile.release]
lto = true
codegen-units = 1