name: Verify PR

on:
  pull_request:
    branches:
      - main

jobs:
  lint-format-build-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Lint
        run: cargo clippy --all -- -D warnings
      - name: Format
        run: cargo fmt --all -- --check
      - name: Build
        run: cargo build
